### ISSUE TITLE
Front CSS Improvement

### ISSUE THREAD

**Issue by turtlepod** [turtlepod/fx-builder#20]
Maybe remove `!important` rule.
and use higher priority to make sure it's loaded early so theme can override it easier.

**Comment by samikeijonen** [comment]
If you want me to take a look at this just let me know.

**Comment by turtlepod** [comment]
thank you @samikeijonen I'll update this thread when I add fix for this issue.

**Comment by turtlepod** [comment]
@samikeijonen I load the CSS on earlier hook so theme css can override it easier.
but unfortunately I'm going to keep the `!important` rule because it make the css cleaner (shorter).

you can test it from `dev` branch.
https://github.com/turtlepod/fx-builder/tree/dev
download zip: https://github.com/turtlepod/fx-builder/archive/dev.zip
