### ISSUE TITLE
.fxb-row-menu .fxb-left { position: absolute } over .fxb-row-menu .fxb-right

### ISSUE THREAD

**Issue by raphaelsramos** [turtlepod/fx-builder#23]
The css position: absolute on .fxb-row-menu .fxb-left is making it be on top of .fxb-row-menu .fxb-right, what make .fxb-row-menu .fxb-right inaccessible.

I've just disable the position: absolute on Chrome DevTools and it fixed.

I'm on Windows / XAMPP local system.

**Comment by turtlepod** [comment]
Thank you @raphaelsramos I forgot to remove that.

Note: I actually also put `width:calc(100% - 125px)` so it will not cover right menu items,
but you are right, the absolute position was not necessary.
