### ISSUE TITLE
Can't break lines on CSS Editor on OS X

### ISSUE THREAD

**Issue by trsenna** [turtlepod/fx-builder#26]
#### What I Expected To Happen

When editing a CSS from admin (I clicked at CSS button at the page-builder do display the CSS editor) I expect to break lines after I press return.

#### What Happened Instead

But when I press return do not break lines. I tested on my OS X, Chrome 53.0.2785.116 and Firefox 43.0.4

#### Steps to Reproduce the Bug

When editing a page from the page-builder tab, click at CSS button. Add a CSS rules and hit enter/return. You will see it's not added a new line as expected.

![screen shot 2016-09-25 at 12 15 44 pm](https://cloud.githubusercontent.com/assets/177555/18816164/f6e4cebc-8319-11e6-8cc9-9dc2566aaff0.png)

**Comment by trsenna** [comment]
Hi,

just to let you know, I could not find any JS error on console. Maybe it's a decision of your to not break lines, or it's something happening on every OS and browsers.

**Comment by turtlepod** [comment]
I actually did that,
but it's a bug :)

I disable it on the form to make sure it didn't publish/submit the form on "enter/return"
but I should not do that in textarea.

thank you for the report.
I'll fix that early tomorrow.
