### ISSUE TITLE
Maybe add friendly developer config/setup

### ISSUE THREAD

**Issue by trsenna** [turtlepod/fx-builder#27]
#### What I Expected To Happen

Probably a suggestion, not a bug... But as a developer I think it's nice to hide Page Builder Settings from final user and defines what pages and custom types should have page-builder support. In other words, the developer can programatically hide the page-builder settings and write an action or filter that grants page-builder functionality at some specific pages or custom post types.

#### What Happened Instead

I just read your code and it's fine now. It's not hard for me as developer to add the behaviour I suggested right before. I just want to let you know that maybe this is a flexibility you would like to keep or make it better/easier later.

What do you think about?

**Comment by turtlepod** [comment]
I'm still thinking about how to properly handle the support for post type.
It's related to #17 

It's actually simply adding post type support "fx_builder"
https://github.com/turtlepod/fx-builder/blob/1.0.0.alpha2/includes/builder/switcher.php#L52

So the settings is simply the wrapper for that.

I'll write a docs via github wiki once i figure this out:
https://github.com/turtlepod/fx-builder/wiki

thank you so much!

**Comment by turtlepod** [comment]
I add a hook to disable settings,
and here's the wiki page https://github.com/turtlepod/fx-builder/wiki/How-to-Disable-Settings

**Comment by trsenna** [comment]
Hi David,

amazing! Thanks very much :)
