### ISSUE TITLE
Custom Post Type settings page saving issue

### ISSUE THREAD

**Issue by wpstudio** [turtlepod/fx-builder#41]
If your site has custom post types, they will show up in the Page Builder "options/settings" page to enable/disable the fx-builder on that cpt.  But when you check a CPT to use fx-builder and press save, the state of the checkbox reverts back to unchecked.

**Comment by turtlepod** [comment]
I can't reproduce the issue.
I tested with WooCommerce, Tribe's Events Calendar, Custom Content Portfolio plugins, and all seem to be working fine.

What CPT plugin are you using? are you register them yourself?

**Comment by turtlepod** [comment]
Closed because no response from @wpstudio
