### ISSUE TITLE
Loss of all data after post edit and Preview Changes

### ISSUE THREAD

**Issue by Smyczek** [turtlepod/fx-builder#45]
#### What I Expected To Happen
Edit page created earlier via Page Builder.

#### What Happened Instead
After Preview Changes or Update, edited page once have and next time don't have content.

#### Steps to Reproduce the Bug
1. Add New Page
2. Enable Page Builder
3. Add Row, Column/Columns and Content
4. Click Publish
5. Go to All Pages
6. Edit New Page
7. Click Preview Changes -> Empty page
8. Disable New tab with empty page
9. Go to All Pages without updating post
10. Again Edit New Page -> Empty page builder

Note: I tested it on local osx machine with MAMP, WP4.7, No other plugins active.

**Comment by turtlepod** [comment]
Just tested and confirmed. you are right.

Thank you for the report!
I'll investigate this bug further.

**Comment by turtlepod** [comment]
@Smyczek I fixed it in dev branch. If you have time can you confirm it's working?
https://github.com/turtlepod/fx-builder/archive/dev.zip

I'll push the update later today.

(it will keep the data on preview, but I still don't know how to make the preview works with page builder)

**Comment by Smyczek** [comment]
Yes, it solved the issue with losing data after Preview. But Preview still doesn't work as it should. Once is ok but next time preview doesn't remember data added via Page Builder. 

After investigation it looks like the Preview mechanism has two different routes. When adress looks similar to this all is ok: `http://example.com/postname/?preview=true `

But next time address looks like this and Preview doesn't display properly: 
`http://example.com/postname/?preview_id=152&preview_nonce=xxx&preview=true`

I found this thread, maybe will help: 
http://wordpress.stackexchange.com/questions/218588/post-preview-mechanism-architecture

**Comment by Smyczek** [comment]
I found probably other issues with this fix.

### What I Expected To Happen
Add New Page using Page Builder

### What Happened Instead
Warning messages when I try Publish New Post.

### Steps to Reproduce the Bug
1. Add New Page
2. Enable Page Builder and insert some data
3. Click Publish -> `Warning: Missing argument 2 for fx_builder\builder\Builder::save() in .../wp-content/plugins/fx-builder-dev/includes/builder/builder.php on line 154`

**Comment by turtlepod** [comment]
thank you so much for all the information. I really appreciate it.
Hmm.. I can't reproduce the `warning` you described.

It's confusing. and there's also "auto draft" stuff happening too.
I'll investigate further. And hopefully able to solve this.

**Comment by turtlepod** [comment]
dang! I really can't find any solution for this preview changes.

In latest commit (dev), I simply hide the "Preview Changes" button.
I'll sleep on it. Recheck everything and push this update tomorrow.

thank you so much.

Note: I still can't reproduce your WARNING issue on new page. Did this still happen in latest commit?

**Comment by Smyczek** [comment]
It is strange, because on one WP installation I have this error message and on another I don't. The same location etc. I will try to find why.
At this stage I can only give you more information about this message. When I turn on Debug Mode I've got more info. Maybe this helps:

```
Warning: Missing argument 2 for fx_builder\builder\Builder::save() in /Applications/MAMP/htdocs/.../wp-content/plugins/fx-builder-dev/includes/builder/builder.php on line 154

Notice: Undefined variable: post in /Applications/MAMP/htdocs/.../wp-content/plugins/fx-builder-dev/includes/builder/builder.php on line 165

Notice: Trying to get property of non-object in /Applications/MAMP/htdocs/.../wp-content/plugins/fx-builder-dev/includes/builder/builder.php on line 165

Notice: Trying to get property of non-object in /Applications/MAMP/htdocs/.../wp-content/plugins/fx-builder-dev/includes/builder/builder.php on line 166

Notice: Trying to get property of non-object in /Applications/MAMP/htdocs/.../wp-content/plugins/fx-builder-dev/includes/builder/builder.php on line 166

Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/.../wp-content/plugins/fx-builder-dev/includes/builder/builder.php:154) in /Applications/MAMP/htdocs/.../wp-admin/post.php on line 197

Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/.../wp-content/plugins/fx-builder-dev/includes/builder/builder.php:154) in /Applications/MAMP/htdocs/.../wp-includes/pluggable.php on line 1179
```

**Comment by turtlepod** [comment]
@Smyczek the the site where the WARNING and NOTICE happen, is there other plugin active? or maybe try to switch to default theme? (twenty*)

https://shellcreeper.com/how-to-debug-wordpress-bug-like-a-boss/

**Comment by Smyczek** [comment]
Only one active plugin is Page Builder. Active theme is Twenty Fifteen. New, clear WP4.7 installation. 
When you testing it, do you have `define('WP_DEBUG', true);` in wp-config.php?

**Comment by turtlepod** [comment]
yes I have wp debug turn on.

**Comment by Smyczek** [comment]
OK. I prepared a live site for test. I send to you login details via contact form on your site (shellcreeper.com). Please check if you see this warning messages there.

**Comment by turtlepod** [comment]
Thank you so much for the sandbox site. I really appreciate it.
This commit seem to fix the fatal error issue: 44e25a3f546560ddac724100567b6096cf81d3ea

I updated the sandbox site with latest dev branch.
feel free to test, and let me know if there's other issue.

again, thank you so much.

**Comment by turtlepod** [comment]
@Smyczek after various debug and hack to solve the fatal error.
I finally found the bug:

This code:
https://github.com/turtlepod/fx-builder/blob/1.0.0/includes/builder/builder.php#L254-L256
```php
remove_action( 'save_post', array( $this, __FUNCTION__ ) );
wp_update_post( $this_post );
add_action( 'save_post', array( $this, __FUNCTION__ ) );
```

should be:
```php
remove_action( 'save_post', array( $this, __FUNCTION__ ) );
wp_update_post( $this_post );
add_action( 'save_post', array( $this, __FUNCTION__ ), 10, 2 ); // forgot the args here.
```

I'll fix and push the update in a couple hours.
Thank you a lot for the bug report and the sandbox site (you can delete/remove my user).
I really appreciate it.

**Comment by Smyczek** [comment]
Yes, it is working now. But when you will have some free time you should find the solution how to turn on Preview functionality. I think it is quite important to see the changes before the post will be Updated.

**Comment by turtlepod** [comment]
yes, you are correct. this feature is very important.
